### ISSUE TITLE
Unhandled :erpc failures

### ISSUE THREAD

**Issue by mjquinlan2000** [cabol/nebulex#140] opened 2021-10-26 17:23 UTC
I am getting a lot of errors while using the Nebulex.Caching decorators which is caused by an unhandled case clause in Nebulex.RPC.rpc_call/6 on rpc.ex:141.

```elixir
    defp rpc_call(_supervisor, node, mod, fun, args, timeout) do
      :erpc.call(node, mod, fun, args, timeout)
    rescue
      e in ErlangError ->
        case e.original do # Line:141 -> fails here
          {:exception, original, _} when is_struct(original) ->
            reraise original, __STACKTRACE__

          {:exception, original, _} ->
            :erlang.raise(:error, original, __STACKTRACE__)
        end
    end
```

The clause that does not match is `{:erpc, :timeout}` and some other `{:erpc, _error}` exceptions. Here is some background about how the app is set up:

erlang 24.1
elixir 1.12.3
running on k8s cluster with a horizontal pod autoscaler (pods created or destroyed dynamically depending on resource usage)
Nebulex set up running Nebulex.Adapters.Partitioned
Node clustering done with [libcluster](https://github.com/bitwalker/libcluster) over kubernetes metadata API. Polling interval is set at 10s (I might lower this to see if that helps).

I think the main solution is to handle the `{:erpc, _error}` clause in a better way, but I'm having a hard time understanding the `:timeout` issue when reading through the erlang documentation. I suspect it has something to do with when the system brings k8s pods down and nebulex is referencing a node that no longer exists.

A secondary concern that I have is when I use the caching decorators there are a number of errors that can arise from not being able to contact other nodes in the cluster and how those errors are handled. It seems to me that right now an error is raised, but this can and has been causing issues with some api requests. Is there a way that I could configure the cache to treat these errors as a "cache miss" so that I can fetch data directly from the data store on an exception without halting the execution? Is there a way for me to set the :erpc timeout explicitly? Also, might my cache configuration be causing issues with this as well?:

```elixir
# cache module
defmodule MyApp.Cache do
  use Nebulex.Cache,
    otp_app: :my_app,
    adapter: Nebulex.Adapters.Partitioned
end

# child spec in application.ex
[{MyApp.Cache, []}, # ... other children]

# config.exs
config :my_app, MyApp.Cache,
  primary: [
    gc_interval: :timer.hours(1),
    backend: :shards
  ]
```

I'm not sure if a multi-level cache would help with this problem (and I probably haven't given this part of the app enough love or done nearly enough research on caching strategies). Any help here would be greatly appreciated.

Thank you

**Comment by cabol** [comment] 2021-10-29 18:30
@mjquinlan2000 just pushed the new feature for caching decorators (#141), please try it out, let me know your thoughts.

**Comment by cabol** [comment] 2021-10-31 10:00
Hey @mjquinlan2000, some thoughts about how you can handle these errors.

1. I think if you are using the caching annotations, with the fixed I posted you can at least ignore them, but not sure how ignoring the errors will affect your application, maybe it is not an issue for you, since if something is now working with the partitioned cache because of an issue with the Elixir cluster, the function block is executed anyways, and once the issue is fixed, the cache will continue working, anyway, let le know if this works for you.

2. Another option I've found very nice is using [retry](https://github.com/safwank/ElixirRetry), it is a very nice library that allows you to handle scenarios like this one. For example, instead of ignoring the errors, perhaps you can retry for some period of time, and as a fallback just return some default value. You can use `retry` in several ways, let me give you a couple of examples:

If you are using/calling the cache directly (without annotations/decorators), you can wrap the logic like:

```elixir
retry with: constant_backoff(1000) |> Stream.take(10), rescue_only: [Nebulex.RPCError] do
  MyPartitionedCache.get(key)
after
  result -> result
else
  _error -> nil
end
```

Or you can use the `@retry` annotation too:

```elixir
@retry with: constant_backoff(1000) |> Stream.take(10), rescue_only: [Nebulex.RPCError]
def some_functions(attrs) do
  values = MyPartitionedCache.get(attrs[:id]) # just an example
  # rest of the logic ...
end
```

And you can also use `@retry` and the caching annotation together, and have something like:

```elixir
@retry with: constant_backoff(1000) |> Stream.take(10), rescue_only: [Nebulex.RPCError]
@decorate cacheable(cache: MyPartitionedCache, key: attrs.id)
def some_functions(attrs) do
  # your logic ...
end
```

I think in this way you can control the RPC error in a better way, even without ignoring them. And the good thing about the `retry`'s approach is that you can use it also with the caching annotations. Anyway, you can try it out, let me know if maybe this works also for you.

Also, as a heads-up, Nebulex v3 is ongoing, and one of the main features is the new API, it will provide an Ok/Error tuple API too (aside from the `!` functions), giving the user the chance to handle the errors. But this is more a mid-term solution because the first release candidate is scheduled by end of January next year.

Wrapping up, try the alternatives out, and let me know your thoughts, I stay tuned!

Thanks!

**Comment by mjquinlan2000** [comment] 2021-11-01 20:34
@cabol I have seen the retry library before, but I have never used it. Most of cache errors that are concerning for me happen on user requests and I'd rather just ignore the error raised and fall back to the db so that I don't keep users waiting. I think the retry library will actually help me with some other areas in the application so I'm going to look into using it. 

After more investigation, it's plain to see that something is causing the pods to crash in k8s and this abrupt termination is what causes the :erpc errors. In all other cases, the Erlang nodes are shut down gracefully and caching is handled correctly. Since the implementation of the mutlilevel cache with local and partitioned was put in, I am only getting a small amount of errors so I am going to try and fix the issue with pods crashing first.

I have not had a chance to look into the new decorator implementation and I am slated to be doing other work for the entire month of November, but it is on my list and I'll try to sneak some testing in.

Thanks

**Comment by cabol** [comment] 2021-11-02 07:47
Sounds good, in the meantime, I will close the issue, but feel free to reopen it and even create a new one if you come across something not working properly, stay tuned, and thanks!

**Closed by cabol** 2021-11-02 07:47 UTC
