### ISSUE TITLE
Error on cache.import using ReplicatedCache

### ISSUE THREAD

**Issue by hazardfn** [cabol/nebulex#86] opened 2020-11-03 15:15 UTC
A new error started popping recently and I am unsure what is causing it:

```erlang
14:34:51.039 [info] module=application_controller line=1943 function=info_exited/3 pid=<0.3054.0> | Application apollo exited: Apollo.Application.start(:normal, []) returned an error: shutdown: failed to start child: Apollo.ReplicatedCache
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, << REDACTED CACHE DATA>>}
            (nebulex 1.2.2) lib/nebulex/adapters/replicated.ex:191: Nebulex.Adapters.Replicated.init/1
            (nebulex 1.2.2) lib/nebulex/cache/supervisor.ex:67: Nebulex.Cache.Supervisor.init/1
            (stdlib 3.13) supervisor.erl:301: :supervisor.init/1
            (stdlib 3.13) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.13) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

We do a rolling upgrade on 2 clustered nodes, the first deploy fails with the above error, if I take down the other node then restart the deploy everything boots up fine. Do you have any hints as to what could be happening, we've been running this for a while and it has just started happening - we haven't really touched Nebulex stuff for a while (short of adding some extra cache entry types along the way).

The `<<REDACTED CACHE DATA>>` is a bunch of items I took out to sanitise any sensitive info that might be leaked but is basically everything I might've expected to show up in the cache. The format is a list of tuples.

**Comment by cabol** [comment] 2020-11-04 13:49
Hey @hazardfn! Let dig into it, in the meantime, could you try moving to the v2? Actually, try to test with the latest changes in the master branch (RC1 will be available soon anyway), it would be helpful to see if this issue is still there. Thanks!

**Comment by hazardfn** [comment] 2020-11-04 14:21
@cabol I ended up finding the issue in the end but not solving the mystery of why it worked for so long before breaking, my best guess is race-condition:

```elixir
children = [
{MyApp.ReplicatedCache, []},
{MyApp.ReplicatedCache.Primary, []}
]
```

Switching the position of those 2 in the supervision tree solved the issue.

To further add to the mystery I did a quick upgrade to v2 to test it without switching those positions and it went back to working again...

**Comment by cabol** [comment] 2020-11-04 17:36
Yeah, that's should be the cause, a race condition as you mentioned, the primary store has to be initialized first, otherwise, there is a high chance this to happen (one of the downsides in v1 is that you have to define the primary cache/store explicitly, and like in this case, rely on the order how they are initialized). On the other hand, in v2 shouldn't happen because one of the improvements was precisely starting the needed caches from the adapter itself, now the partitioned and replicated adapter take care of initializing the primary store, so you only have to define the replicated cache in your case:

```elixir
children = [
  {MyApp.ReplicatedCache, []}
]
```

And the cache should be:

```elixir
defmodule MyApp.ReplicatedCache do
    use Nebulex.Cache,
      otp_app: :my_app,
      adapter: Nebulex.Adapters.Replicated
end
```

> No need to define the primary store explicitly anymore, it is handled by the adapter.

I will run more tests just in case anyway!

**Comment by cabol** [comment] 2020-11-06 18:48
Hey! After some tests with v1.2, I was able to reproduce the error just to be sure it is because of a race condition as you pointed out (due to the replicated cache starts before its primary cache). Starting the replicated cache before the primary one, and forcing the primary cache to delay a bit before to start, I got this error (which I suppose it is the same as you got):

```elixir
** (Mix) Could not start application demo: Demo.Application.start(:normal, []) returned an error: shutdown: failed to start child: Demo.Cache
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, [5837, 6330, 8727, 1659, 646, 9044, 7122, 2419, 4492, 8009, 9588, 8819, 2119, 6214, 9296, 6468, 5481, 6860, 4147, 2495, 8792, 2756, 4922, 2090, 6145, 1684, 9057, 5829, 2459, 983, 1306, 1221, 2771, 6682, 4191, 9000, 2852, 907, 1975, 8416, 7006, 961, 4735, 8859, 5547, 2665, 2265, 1728, ...]}
            (nebulex 1.2.2) lib/nebulex/adapters/replicated.ex:191: Nebulex.Adapters.Replicated.init/1
            (nebulex 1.2.2) lib/nebulex/cache/supervisor.ex:67: Nebulex.Cache.Supervisor.init/1
            (stdlib 3.12) supervisor.erl:295: :supervisor.init/1
            (stdlib 3.12) gen_server.erl:374: :gen_server.init_it/2
            (stdlib 3.12) gen_server.erl:342: :gen_server.init_it/6
            (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

I also confirmed by switching the order and ensuring the primary cache starts always before the replicated one and with this change, the error doesn't happen. So, I think we can confirm the assumption it was because of a race condition because of the order in which the caches are started (in v1). Additionally, I checked the same with Nebulex v2 and the issue doesn't happen either.

I will close the issue but feel free to reopen it if even with this fix the issue shows up again.

PD: You should migrate to v2 anyway, the RC1 will be ready soon!

Thanks!

**Closed by cabol** 2020-11-06 18:48 UTC
