### ISSUE TITLE
Asynchronous testing struggles

### ISSUE THREAD

**Issue by bkowalk** [cabol/nebulex#72] opened 2020-05-21 21:14 UTC
Thanks for the awesome utility! Using this in a project right now. Absolutely an amazing tool.

I've run into one issue while trying to build unit tests around Nebulex - it seems that to have fully isolated and asynchronous tests, a different cache would need to be defined for each test and then injected into functions. It seems that's the case in Nebulex's unit tests as well (looking primarily at `hooks_test.exs` and at those caches' definitions in `test-cache.ex`). 

As a quick example, these two tests are running asynchronously. The `set_lock` and `check_lock` functions each use Nebulex's `set` and `get` functions to work with the cache. If the first runs before the second, everything goes fine. If the second runs first, during its sleep command the first will most likely run (changing the lock's expiration from one second to 30). The test then fails as their cache keys have collided and changed each other's values.

```
    test "sets lock in cache" do
      assert {:ok, :complete} == Locks.set_lock("lock_key", "token", 30)
      assert "token" == LockCache.get("lock_key")
    end

    test "automatically removes lock after a set expiration period" do
      Locks.set_lock("lock_key", "token", 1)
      assert {:locked, "token"} == Locks.check_lock("lock_key")
      Process.sleep(1100)
      assert {:unlocked, nil} == Locks.check_lock("lock_key")
    end
```

Just wondering if there is a way around this if I want to make sure to isolate tests per unit test - is that currently possible? Or would the recommended solution just be to mock this out at all levels possible, then at any level that needs to run directly against Nebulex, ensure different keys are used? If the latter, I'd love to recommend some sort of sandboxing like this (and potentially could help out, if you're open to it) as a feature.

Thanks in advance for any thoughts!

**Comment by cabol** [comment] 2020-05-22 07:51
Hey @bkowalk, thank you very much for your comments and feedback 😄 !

> I've run into one issue while trying to build unit tests around Nebulex - it seems that to have fully isolated and asynchronous tests, a different cache would need to be defined for each test and then injected into functions. It seems that's the case in Nebulex's unit tests as well (looking primarily at hooks_test.exs and at those caches' definitions in test-cache.ex).

It is not like that, the reason I have in the tests different caches is that I'm defining different config on them, and most of those config properties are defined in compile-time. But actually, if you take a look at the [local adapter test](), you will see it uses the same cache for the [shared object test](https://github.com/cabol/nebulex/blob/master/test/shared/cache/object_test.exs), and that's only one example, there are several tests like that.

> As a quick example, these two tests are running asynchronously. The set_lock and check_lock functions each use Nebulex's set and get functions to work with the cache. If the first runs before the second, everything goes fine. If the second runs first, during its sleep command the first will most likely run (changing the lock's expiration from one second to 30). The test then fails as their cache keys have collided and changed each other's values.

Could you please share what you have in the `setup` for those tests you are running?

My suspicion is there is nothing related to the cache itself, and it is being started with your app automatically when the tests run. Nebulex works very similar like Ecto, if you define a Cache that is started in your app supervision tree, during the tests that cache is shared among those tests, so yes, there might be race conditions. Ecto, for example, uses the sandbox for handling this, unfortunately, there is no sandbox adapter yet in Nebulex, BUT there is a very simple way what I use a lot myself, flush the cache in the setup, like so:

```elixir
setup do
  LockCache.flush()
end
```

This ensures the cache is empty before running a test, which makes the test cases completely autonomous.

The other option, perhaps it is not that simple, and it is the one I use myself for Nebulex tests, as you see in the examples put above, in the setup, the Cache is started and terminated explicitly, which ensures also the cache is empty before running a test and having isolated test cases.

Please let me know if it was useful for you, otherwise, you may provide more info so I can help you out. Stay tuned!

**Comment by bkowalk** [comment] 2020-05-22 15:46
Thanks so much for the quick response and for the help! Unfortunately, we've tried a lot of these (and I've just retried again) and are still having trouble truly isolating asynchronous test cases... 

> But, if what you have is, two different test cases (two test modules) with their own internal tests and you use the same cache for both, there might be race conditions yet. If that is the case, perhaps you should run the tests with async off. I'll check if there might be another way anyways!

I  believe this may be the case - we've got modules throughout our app that use these locks, so we're trying to isolate all of them from each other. With `async: false`, things definitely work! Just hoping to find a way around that as `async: true` is our company testing standard and I'd hate for future devs following that standard to wonder why their tests are occasionally failing if they hit the LockCache!

> Could you please share what you have in the setup for those tests you are running?

So we've tried a couple of different ways of configuring the setup block, and don't seem to be having much luck. First, we tried the app supervision tree (as you supposed). That worked stably, but with the race conditions you'd expect. Second, we've tried mirroring the setup you've used in your tests. A couple notes: this is in our ExUnit case template, so it applies to all tests regardless of module. Additionally, this LockCache is using the Replicated adapter, using Primary as our local cache:

```
  setup do
    caches_and_pids = start_caches([
      DeepImpact.Data.Cache.LockCache,
      DeepImpact.Data.Cache.LockCache.Primary
    ])
    :ok

    on_exit(fn ->
      stop_caches(caches_and_pids)
    end)
  end

  ## Helpers
  defp start_caches(caches) do
    for cache <- caches do
      {:ok, pid} = cache.start_link()
      {cache, pid}
    end
  end

  defp stop_caches(caches_and_pids) do
    for {cache, pid} <- caches_and_pids do
      :ok = Process.sleep(10)
      if Process.alive?(pid), do: cache.stop(pid)
    end
  end
```

When we run in this way, though, we just keep getting this exception back:
```
3) test set_lock/2 sets lock in cache (DeepImpact.Data.LocksTest)
     test/deep_impact/data/locks/locks_test.exs:57
     ** (MatchError) no match of right hand side value: {:error, {:already_started, #PID<0.539.0>}}
     stacktrace:
       (deep_impact 0.1.0) test/support/repo_case.ex:36: anonymous fn/2 in DeepImpact.RepoCase.start_caches/1
       (elixir 1.10.1) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
       (deep_impact 0.1.0) test/support/repo_case.ex:35: DeepImpact.RepoCase.start_caches/1
       (deep_impact 0.1.0) test/support/repo_case.ex:18: DeepImpact.RepoCase.__ex_unit_setup_1/1
       (deep_impact 0.1.0) test/support/repo_case.ex:1: DeepImpact.RepoCase.__ex_unit__/2
       test/deep_impact/data/locks/locks_test.exs:1: DeepImpact.DataLocksTest.__ex_unit__/2
```

I'm assuming that this is due to the cache being started by multiple modules, and the cache then trying to register itself by name. I do find this a little strange still, though, as your tests are running async and have this in the setup block (so potentially, each of the tests could still start at the same time), but still don't collide... I'm fairly new to Elixir, so please let me know if I'm missing something obvious here!

Finally, we've tried using the other method you suggest - flushing before each run (using exactly the one-liner setup you've mentioned above). When we did, we were still running into race conditions with various tests failing. The biggest telltale was this one, which re-hydrates cache if it ever finds that less than 90% of our Postgres DB is represented there:

```
    test "runs if ETS is lower than 90%, successfully pulls in PG records" do
      card = insert(:card)
      assert CardCache.get(card.card_token) == nil
      assert Hydrator.run_if_needed() == {:ok, :rehydrated}
      assert CardCache.get(card.card_token) == {:ok, card}
    end
```

When run, this test would sometimes fail as the code would compare our PG records (just one, based on that insert on the first line) with items in cache (expected to be 0 in the test, but could be 1 or more if another test is currently using) and would not run the hydrator as the cache appeared to be filled. It seems from what you're saying that the flush() method would only fully work for synchronous tests, yes? Otherwise, async tests sharing a single cache could potentially be flushing cache in the middle of another test process, or alternatively two tests could potentially still be adding in their data at the same time.

Hopefully that shares enough context about what we're running into. Would love your thoughts if you think there's a way around this, or if there could be something I'm missing!

Really appreciate the help! Thanks again!

**Comment by cabol** [comment] 2020-05-23 07:18
I see, so I'll check if there is a better way to address it!

**Comment by cabol** [comment] 2020-05-25 09:04
Hey, just a quick update, I'm working on something I think it may help to run the tests in `async` mode, I'll try to push it as soon as possible, thanks!!

**Comment by bkowalk** [comment] 2020-05-25 13:28
Wow already? You’re a freaking superhero! Thanks! Excited to see it.

**Comment by cabol** [comment] 2020-06-06 19:05
Hey! I haven't forgotten the issue, in fact, I wanted to give you some news. 

The issue is fixed but it will be available since v2 because the current/previous version is very attached to resolve options in compile-time, which makes things much harder, especially for this problem. The good news is the first release candidate for v2 is almost ready, I'll publish it by the end of June. In the meantime, you can try out the [branch `v2.0.0`](https://github.com/cabol/nebulex/tree/v2.0.0), you will see the tests are using the same cache, I added the same feature Ecto has for dynamic repos but for having dynamic caches, with this is very easy to achieve what you want, having isolated tests using the same cache definition.module.

It would be great if you try it out and also give your feedback, v2 brings with a lot of improvements in terms of performance, flexibility, usability, and so on. The doc is updated already, each adapter has documented the new features and improvements and also examples. Please let me know if you need any help with anything, stay tuned!

**Comment by bkowalk** [comment] 2020-06-08 17:30
`put_dynamic_cache` FTW! This is awesome. Just played around with our code for a while and adjusted to 2.0.0 syntax, then tried putting dynamic caches in front of our tests. All were able to run as async happily. Moving that into our case block would solve this permanently.

How far out would you ballpark a 2.0.0 release to be? Excited to get to use it! Thanks for all the awesome work on this and for making this awesome tool in the first place!

**Comment by cabol** [comment] 2020-06-09 09:49
> put_dynamic_cache FTW! This is awesome. Just played around with our code for a while and adjusted to 2.0.0 syntax, then tried putting dynamic caches in front of our tests. All were able to run as async happily. Moving that into our case block would solve this permanently.

Glad to hear that 😄 !!

> How far out would you ballpark a 2.0.0 release to be? Excited to get to use it! Thanks for all the awesome work on this and for making this awesome tool in the first place!

The first release candidate `v2.0.0-rc.0` will be published by the end of this month. Then, the idea is to let people try it out and meanwhile fix the Redis adapter to the v2 (also new features and enhancements). So most likely, the `v2.0.0` will be published by the end of August (worst case, it may be published earlier).

Thanks and stay tuned 👍 !!

**Comment by cabol** [comment] 2020-07-05 09:06
Fix already merged in master along with the base for v2.

**Closed by cabol** 2020-07-05 09:06 UTC
