### ISSUE TITLE
Invalidate keys cluster-wide

### ISSUE THREAD

**Issue by BartOtten** [cabol/nebulex#18] opened 2018-02-09 11:01 UTC
Currently keys which are set are available for the whole cluster, multilevel style. Could a function be added to invalidate the keys cluster-wide?

**Over simplified exampe:**
Node1: Nebulex.set "foo" "bar"
>> bar
Node2: Nebulex.get "foo"
>> bar
Node2: Nebulex.drop "foo"
>> nil (or last value)
Node1: Nebulex.get "foo"
>> nil

**Comment by BartOtten** [comment] 2018-02-09 11:32
After a second thought and seeing the delegates, this might as well be a bug.
`defdelegate delete(key, opts \\ []), to: One.MultiCache.Dist`

Also, I see no real value in deleting only from the Local cache in a cluster, as 'get' would still get a value from L2 :)

**Comment by cabol** [comment] 2018-02-11 19:00
@BartOtten if i understand you correctly, what you want to do is delete the key from all cache levels when `Nebulex.delete` is executed right? If so, you can do this:

```elixir
MyCache.delete("foo", level: :all)
```

That should remove the key in all cache levels, if you find any issue please let me know. On other hand, I agree when you say *"I see no real value in deleting only from the Local cache in a cluster, as 'get' would still get a value from L2"*, mayde the default behaviour should be delete the key from all cache levels, I'll check it out!!

Please let me know if that solves your issue, stay tuned, thanks :)

**Comment by BartOtten** [comment] 2018-02-11 19:17
I haven’t tried yet, but my demo had 2 connected Elixir nodes, which were
connected caches using NearCache (like: the example on 2 nodes). Delete on
node 1 had no effect cause the value would be fetched at node 2.

As a workaround I hacked in my code a drop/1 function, which rpc to all
nodes and executes MultilevelCache.delete

If you option has the same effect, i rather use that. If not, delete/2 is
broken on multiple node environments.


Op zo 11 feb. 2018 om 20:00 schreef Carlos Andres Bolaños R.A. <
notifications@github.com>

**Comment by cabol** [comment] 2018-02-15 12:14
@BartOtten were you able to try `MyCache.delete("foo", level: :all)`? Let me know if it did work for you or not. Stay tuned!

**Comment by BartOtten** [comment] 2019-05-09 15:01
I checked this issue last night(finally), but the current behavior does not seem to fix it. 

It's true the key is deleted from all caches of the  node delete/2 is called at (node 1), but if one of the other nodes (node 2.....x) already did a get/1 they will still return the value as they still have the key in their local cache.

The  expected  behavior is that when delete is called at node 1, no matter what, no other nodes will be able to retrieve the value other than nil. So the given key should be deleted on on every node connected in every cache level.

**Comment by cabol** [comment] 2019-05-09 15:10
So if I understand correctly, the issue is when you have a Near cache, which is, a multilevel cache where the L1 is the local one and the L2 is the distributed one. And, when you perform a `delete` from Node1, it is deleted from the Node1 local cache and also deleted from the distributed cache in the rest of the nodes, BUT only the distributed cache, not from the local cache in the other nodes. 

I'll check this out!

**Comment by cabol** [comment] 2019-05-09 15:33
@BartOtten I was looking into the [NearCache topology documentation](https://docs.oracle.com/cd/E14526_01/coh.350/e14510/nearcache.htm#COHGS229), and there are 4 possible strategies for keys invalidations. The current strategy implemented is the first one, which is **"none"**:

> This strategy instructs the cache not to listen for invalidation events at all. This is the best choice for raw performance and scalability when business requirements permit the use of data which might not be absolutely current. The freshness of data can be guaranteed by the use of a sufficiently brief eviction policy for the front cache.

So it would be nice to support another strategy to tackle this issue out, maybe the **"Present"** strategy:
	
This strategy instructs the Near Cache to listen to the back cache events related only to the items currently present in the front cache. This strategy works best when each instance of a front cache contains a distinct subset of data relative to the other front cache instances (for example, sticky data access patterns).

So I'd like to propose to create a separate ticket to address it, it would be like: "Implement Present strategy for invalidation in NearCache topology".

**Comment by cabol** [comment] 2019-05-09 16:09
I'll close this issue so we can continue the discussion and follow up of this #50

**Closed by cabol** 2019-05-09 16:09 UTC
