### ISSUE TITLE
Rolling deployment after adding the cache does not start new nodes

### ISSUE THREAD

**Issue by philipgiuliani** [cabol/nebulex#107] opened 2021-03-16 08:15 UTC
Hi,

we have set up a rolling deployment but after adding Nebulx with the Replicated Adapter, our new nodes are not able to start up because of the following exception:
```
State: %{cache: XXXXX.Cache, name: XXXXX.Cache, primary_name: nil, retries: 0, stats: false, task_sup: nil}
17:42:09.644 [error] GenServer XXXXX.Cache.Bootstrap terminating
** (KeyError) key :responses not found in: [action: :sync_data, errors: [badrpc: {:EXIT, {:undef, [{XXXXX.Cache.Primary, :reset_generation_timer, [], []}, {Nebulex.Adapters.Replicated, :with_dynamic_cache, 3, []}]}}]]
    (elixir 1.11.3) lib/keyword.ex:420: Keyword.fetch!/2
    (nebulex 2.0.0) lib/nebulex/exceptions.ex:42: Nebulex.RPCMultiCallError.exception/1
    (nebulex 2.0.0) lib/nebulex/adapters/replicated.ex:637: Nebulex.Adapters.Replicated.Bootstrap.handle_multicall/1
    (nebulex 2.0.0) lib/nebulex/adapters/replicated.ex:546: Nebulex.Adapters.Replicated.Bootstrap.handle_info/2
    (nebulex 2.0.0) lib/nebulex/adapters/replicated.ex:557: Nebulex.Adapters.Replicated.Bootstrap.handle_info/2
    (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :timeout`
```

The exception comes from here and raises an Exception if the cache is not running on all connected nodes: https://github.com/cabol/nebulex/blob/master/lib/nebulex/adapters/replicated.ex#L628

**Comment by cabol** [comment] 2021-03-21 07:23
Hi, let me look into it. However, I see there is a bug when raising the exception, I will push a fix, despite it is not the cause of the issue it can give us a clearer error stack trace.

**Comment by cabol** [comment] 2021-03-21 08:06
Hey @philipgiuliani, I just pushed a fix to master for the exception issue (#108 ), it won't fix the issue itself but we should see the right exception now. If you can try it out and paste the new stack-trace would be great.

On the other hand, about the issue, you mentioned `The exception comes from here and raises an Exception if the cache is not running on all connected nodes`. This is a validation to ensure all nodes are running the cache, so can you give me more information about your scenario, for example:

- Why the cache is not running in all the nodes in your case? is it because of a race condition or is there any other reason?
- Is this happening when you start the nodes one after the other, or once you have the cluster, you add new nodes? I need to know more details about the scenario so I can reproduce the error.

Thanks and I stay tuned!

**Comment by cabol** [comment] 2021-04-08 19:43
Any feedback on this @philipgiuliani ?

**Comment by philipgiuliani** [comment] 2021-04-09 09:20
Hi @cabol,

sorry for the late reply.

> Why the cache is not running in all the nodes in your case? is it because of a race condition or is there any other reason?

This actually will only happen after the very first deployment after adding Nebulex to the Project.
We had 4 Nodes running with our application version 1.2.0 (without Nebulex). We have added Nebulex in 1.3.0 and when deploying it the new nodes could not start because Nebulex was not running on the 1.2.0 Nodes. The solution was just to stop all Nodes and do a clean start.

We are using a rolling deployment strategy to prevent any downtime of our productive system.

> Is this happening when you start the nodes one after the other, or once you have the cluster, you add new nodes? I need to know more details about the scenario so I can reproduce the error.

Once the Cluster with all 1.3.0 nodes was up, we have not experienced any problems in the next deployments.

---

Reproducing this with your latest update will not be as easy for me since I have to remove Nebulex and do another deployment. But I think this could easily be tested locally.

**Comment by cabol** [comment] 2021-05-01 11:34
Hey @philipgiuliani! Sorry for the lateness, but actually I've been working on several improvements for the replicated adapter in particular. I tried to reproduce the error with the scenario you described above, starting some nodes without Nebulex, and others with Nebulex, but all nodes connected to each other. The replicated cache, since it uses `:pg`/`:pg2` underneath to retrieve the nodes that belong to the replicated cache cluster, it doesn't take into account the ones not running the replicated cache (which is the expected behavior), therefore, I couldn't reproduce the error. Anyhow, as I mentioned previously, I have pushed several improvements to the replicated adapter, especially related to the bootstrap/sync process, and also handling replication errors properly. So, I will close the issue for now, but feel free to reopen it if you come across the same error again. Stay tuned, thanks!

**Closed** 2021-05-03 14:54 UTC
